spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

server:
  error:
    include-stacktrace: on_param